dist: bionic
sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.4
  - 7.3
  - 7.2

env:
  matrix:
    - Laravel=8.x
    - Laravel=7.x
    - Laravel=6.x

matrix:
  exclude:
    # Unsupported combinations
    - { env: Laravel=8.x, php: 7.2 }

before_install:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - travis_retry composer require --dev "laravel/framework:${Laravel}" --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
