name: tests

on:
  # Run action on every push
  push:
    
  # Run action at midnight to test against any updated dependencies
  schedule:
  - cron: '0 0 * * *'

jobs:
    phpunit:
        strategy:
            matrix:
                php: [7.4, 7.3, 7.2]
                laravel: [8.*, 7.*, 6.*]
                os: [ubuntu-latest, windows-latest]
                
                # Unsupported combinations
                exclude:
                - laravel: 8.*
                  php: 7.2
            
            # Continue running through matrix even if one combination fails
            fail-fast: false

        runs-on: ${{ matrix.os }}
        
        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.os }}

        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - name: Install dependencies
              run: |
                    # Install Laravel version per matrix
                    composer require --dev "laravel/framework:${{ matrix.laravel }}" --no-interaction
                    
                    # Run against latest deps
                    composer update --no-interaction

            - name: Execute PHPUnit tests
              # Update snapshots each time to deal with platform differences
              # @see https://github.com/spatie/phpunit-snapshot-assertions/issues/105
              run: vendor/bin/phpunit -d --update-snapshots --coverage-clover build/logs/clover.xml
              
            - name: Report code coverage to Coveralls
              uses: coverallsapp/github-action@master
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
